name: Publish Quarto Site

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      
      - name: Install Python dependencies
        run: pip install -r textbook/requirements.txt
      
        # if we need any other like R, add here

      - name: Render Quarto
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: ./textbook/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: textbook/_book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
